### PR TITLE
Fix Ratings/Missing seasons/episode info for plex web version 3.11

### PR DESCRIPTION
**Pull request by JourneyOver**
Added new classes for the web version 3.11, this fixes both issue #6 and issue #7, have tested a bit and everything seems to be in working order at least on my end. (Can't promise they will work when 3.12+ releases but I'll be keeping an eye on the "https://app.plex.tv/web" releases as I have a stylesheet that I have to keep updated as well.)

Went ahead and upped the version # to 1.5.4 but you can change that if you want.

### CODE REVIEW

**Comment by campanflaviu** [comment]
Seems to work fine on my side. 
Thanks for fixing this!
Maybe I'll look into a better way to select the elements without having to rely on auto-generated class names which could change on a server update, but we'll see. If that doesn't happen we could leave it as it is.

**Comment by JourneyOver** [comment]
I swear the plex devs are just fucking with people or something >..> They switched back to the old css classes again lol.. Since I kept the old css classes in along with the new additions that I had made in this pull request 3 days ago nothing needs to be changed.

**Comment by campanflaviu** [comment]
have you received any server updates? I'm on 3.14.1 and works fine for me. Maybe they reverted back again?

**Comment by JourneyOver** [comment]
No server updates haven't been pushed out for a good while yet to the public, public releases are still sitting at Version 3.9.1 for web releases, and I know things are working fine xD for 3.14+ so far. 
I was saying that they reverted back to the old css classes from before the 3.11 class changes, and since I kept the old classes in when I went and added the classes for 3.11 you don't have to change anything as it had both classes from before 3.11 and during the 3.11 changes.

**Pull request merged**
